api_uri: "http://localhost/zabbix/"
login_user: "Admin"
login_pass: "zabbix"
num_hosts: 10
hosts_step: 0
host_group: "Linux servers"
custom_agents:
 - ip_address: "127.0.0.1"
   port: 10050
zabbix_log_file: "/var/log/zabbix/zabbix_server.log"
data_file_path: "output/dbsync-average.dat"
warm_up_duration: 60
