uri: "http://localhost/zabbix-postgresql/"
login_user: "Admin"
login_pass: "zabbix"
num_hosts: 10
hosts_step: 0
host_group: "Linux servers"
template_name: "Template_Linux_5sec"
agents:
 - ip_address: 192.168.1.10
   port: 10050
zabbix_log_file: "/var/log/zabbix/zabbix_server_postgresql.log"
data_file_path: "output/dbsync-average.dat"
warm_up_duration: 10
