uri: "http://localhost/zabbix/"
login_user: "Admin"
login_pass: "zabbix"
num_hosts: 10
hosts_step: 0
host_group: "Linux servers"
template_name: 
custom_agents:
 - ip_address: "127.0.0.1"
   port: 10050
zabbix_log_file: "/var/log/zabbix/zabbix_server.log"
rotate_zabbix_log: true
data_file_path: "output/dbsync-average.dat"
warmup_duration: 60
histories:
 - host: "Zabbix server"
   key: "system.cpu.util[,system]"
   path: "output/cpu-system.dat"
 - host: "Zabbix server"
   key: "system.cpu.util[,user]"
   path: "output/cpu-user.dat"
 - host: "Zabbix server"
   key: "system.cpu.util[,iowait]"
   path: "output/cpu-iowait.dat"
 - host: "Zabbix server"
   key: "system.cpu.util[,idle]"
   path: "output/cpu-idle.dat"
